run:
  tests: true

linters:
  enable:
    - gofmt
    - gocritic
    - errorlint
    - depguard
    - forbidigo

linters-settings:
  # copied from depguard github example
  depguard:
    rules:
      allow_project_packages:
        list-mode: original
        files:
          - $all
          - "!$test" # Exclude test files if needed
        allow:
          - $gostd # Always allow Go standard library
          - github.com/afa7789/skene
          - fyne.io/fyne/v2
          - github.com/nicksnyder/go-i18n/v2
          - golang.org/x/text/language
        deny:
          - pkg: io/ioutil
            desc: "Replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"

issues:
  exclude:
    - composite
